### ISSUE TITLE
Kompatibilität mit Contao Version 4.7.x

### ISSUE THREAD

**Issue by wugu** [MetaModels/attribute_translatedcheckbox#14]
Gibt es bestimmte Gründe, warum die Erweiterung nicht kompatibel mit Contao 4.7.x ist?
Getestet wurde diese mit der Contao Version 4.7.2.

Eine Unstimmigkeit ist mir hier aufgefallen:

Auszug aus der composer.json der Erweiterung:
`````
  "require": {
    "symfony/dependency-injection": "^3.3"
  },
`````

In den anderen kompatiblen MetaModel-Bundles wurde diese Abhängigkeit so gesetzt:
`````
  "require": {
    "symfony/dependency-injection": "^3.3 || ^4.0"
  },
`````

Weiß jemand mehr?

**Comment by zonky2** [comment]
btw: https://metamodels.readthedocs.io/de/latest/manual/install.html#installation-von-mm-2-1

**Comment by discordier** [comment]
Hat einfach noch keiner angepasst. Installierbar ist es jedoch unter 4.7.x, ansonsten wyrde travis schon lange schreien.

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/attribute_translatedcheckbox/pull/16
