### ISSUE TITLE
The translatedcheckbox does not save the unchecked setting in an other language then the fallback language, when the fallback language is checked.

### ISSUE THREAD

**Issue by heimseiten** [MetaModels/attribute_translatedcheckbox#15]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedcheckbox/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |  7.3        |                                  |
| Contao version:                     |    4.7.5      |                                  |
| MetaModels version:                 |   2.1.1       |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    core & attribute_translatedcheckbox      |                                  |

## Issue description

The translatedcheckbox does not save the unchecked setting in an other language then the fallback language, when the fallback language is checked.

## Steps to reproduce

1. Check the checkkbox in fallback language.
2. Uncheck the checkbox in an other language and click save. 

## Describe the behaviour of the application

The system does not save the setting.

## Describe the expected behaviour of the application

The system should save the setting.

**Comment by zonky2** [comment]
pls update https://github.com/MetaModels/attribute_translatedcheckbox/commit/c91665e931abbbfb40392750f90f88fb55e21b06 and check

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@heimseiten could you please have a final look at this and tell if your issue has been resolved?

**Comment by heimseiten** [comment]
It works perfect now. Thank you!
