### ISSUE TITLE
Sub-Bereich kann nicht erstellt werden.

### ISSUE THREAD

**Issue by jonasbuechel** [MetaModels/attribute_translatedcheckbox#2]
In der Eingabemaske kann kein Sub-Bereich erstellt werden. Das Icon bleibt ausgegraut und kann nicht geklickt werden.

Getestet mit: 
Contao: 3.2.9
Metamodels: dev-contao3 vom 27.04.2014
attribute_translatedcheckbox: dev-contao3 vom 30.04.2014

**Comment by xantippe** [comment]
@jonasbuechel 
* was meinst Du mit "Sub-Bereich"? eine "Subpalette"? https://now.metamodel.me/de/aktuelles/details/fundraising-fuer-subpaletten
* welches Icon bleibt ausgegraut?

**Comment by discordier** [comment]
@xantippe kann das zu?

**Comment by xantippe** [comment]
da @jonasbuechel nicht antwortet und aus meiner Sicht alles i.O. - ja, ich mache zu...
