### ISSUE TITLE
Listview zeigt 'Auge' der aktuellen Sprache an, obwohl die nicht als Übersetzung verfügbar ist

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_translatedcheckbox#20]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedcheckbox/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     php7.4     |                                  |
| Contao version:                     |     4.9.12     |                                  |
| MetaModels version:                 |     2.2     |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |    all      |                                  |

## Issue description

Ich habe ein MM Produkte, das Mehrsprachig ist (en und fr). en -> Fallback
Eine translated_checkbox für die Visibiliity.
Im Backend bin in in der deutschen Sprache unterwegs.
Mir werden jetzt 3 Augen angezeigt (de, en , fr).
Ich kann den Zustand auch per Klick umschalten (grünes/graues Auge) und der Zustand wird auch gespeichert bei allen drei Sprachen.

Wenn ich meine Sprache im Backend umstelle auf Englisch bekomme ich auch nur noch die 2 gewünschten Augen (en, fr) angezeigt und de ist weg.
Das ganze funktioniert so nicht nur mit de, sondern auch mit anderen Sprachen (getestet mit nl).

## Describe the expected behaviour of the application
Es sollten von Anfang an immer nur zwei Augen angezeigt werden (en und fr) und nicht noch zusätzlich die Sprache, in der man im Backend angemeldet ist.

**Comment by zonky2** [comment]
@discordier this 
https://github.com/MetaModels/attribute_translatedcheckbox/blob/f6ce22c508a2213bf0328167a438b4e6d51ce118/src/EventListener/BuildMetaModelOperationsListener.php#L100-L106
add a toggle icon for active language - if active language (BE) not in `getAvailableLanguages`, we have one icon more...

I think the block is superfluous.

**Comment by discordier** [comment]
It is not superfluous but there is a check missing if the current language is contained at all.
The foreach below correctly filters it out if present, however it is never checked it it is there in the first place.

The whole reason is to have the current language always the first button.

**Comment by zonky2** [comment]
I think it is wrong to set the current language of the backend to first position, because the position could change when the language is changed - "GUI-GAU".

Either the fallback language at first position or completely in the order in which the languages are defined and arranged.

**Comment by zonky2** [comment]
fixed in MM 2.2
