### ISSUE TITLE
Icons für die Listenansicht je Sprache einstellbar machen

### ISSUE THREAD

**Issue by cogizz** [MetaModels/attribute_translatedcheckbox#3]
Das Feature aus https://github.com/MetaModels/attribute_checkbox/issues/3 sollte ggf. auch in das TranslatedAttribute übertragen werden, oder?

**Comment by xantippe** [comment]
@cogizz wie siehts aus - kannst Du das übernehmen?

**Comment by zonky2** [comment]
welche "Auskunft" erhält der User im BE mit dem Icon und wie soll die Implementierung aussehen?

Soll es für jede Sprache ein Icon-Double geben oder eins für alle?

Derzeit gibt es in der Listenansicht keine Umschaltung der Sprache - also welchen Zustand zeigt man an insbesondere bei dem Fall, man hat das BE in Deutsch aber die MM Sprachen z.B. als EN + FR?

**Comment by MacKP** [comment]
Oh, ich bin da auch gerade mal wieder drüber gestolpert. Wäre schon nett. Mit 7 oder mehr Augen sieht das etwas blöd aus und ist recht unpraktisch ;-)

**Comment by zonky2** [comment]
wie immer - wie siehts mit einem Auftrag ans MM-Team aus?

**Comment by MacKP** [comment]
Aktuell nicht. Wenn ich was hab melde ich mich ;-)

**Comment by zonky2** [comment]
Fixed in MM 2.2
