### ISSUE TITLE
Rework to Events

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_translatedcheckbox#8]
@discordier https://github.com/MetaModels/attribute_translatedcheckbox/tree/rework-to-events bist Du damit fertig, oder fehlt hier noch was?

**Comment by discordier** [comment]
die registrierung der events sollte noch in config/event-subscribers.php wandern, ansonsten kann man es glaube ich mergen.
Was meinst du?

**Comment by discordier** [comment]
Habe es nach tng gemerged. Ist nun ab c93dfecd318d6afb7132cfe4e1d75b405ff35be2 drin.

**Comment by discordier** [comment]
Ref: MetaModels/core#698
